### ISSUE TITLE
Bootstrap a hard requirement y/n?

### ISSUE THREAD

**Issue by musicformellons** [kartik-v/bootstrap-star-rating#125]
I tried to find out whether Bootstrap is a hard requirement.

The following suggests it is a hard requirement:
The name bootstrap-star-rating suggests very much that Bootstrap is a hard requirement.
http://plugins.krajee.com/star-rating says "JQuery star rating plugin for Bootstrap".

But I also find following:
The themes seem to make the bootstrap redundant...?!
And http://plugins.krajee.com/star-rating says under "Pre-requisites": "Bootstrap 3.x is optional and used by default, but can be overridden to use any CSS".

As so far -although following your docs closely- I did not manage to get it working without Bootstrap could you please explain whether it can work without Bootstrap and maybe give an example how to set it up?

**Comment by kartik-v** [comment]
It can work without bootstrap - for example you must read the theming functionality - where you can set your own theme config and set the `theme` property, then set your own CSS and fonts to override (since the `theme-<themename>` CSS selector will be appended to the container which you can override to style your own)

Examples of variants provided:

- [Font Awesome theme](http://plugins.krajee.com/star-rating/demo#theme-fa)
- [Krajee Unicode theme](http://plugins.krajee.com/star-rating/demo#theme-uni)
- [Krajee SVG theme](http://plugins.krajee.com/star-rating/demo#theme-svg)

**Comment by musicformellons** [comment]
Thanks for your swift answer! I will try some more then!

**Comment by musicformellons** [comment]
@kartik-v I got it working without bootstrap now. I do have an issue when bundling star-rating.js using webpack. Other files bundled (css) are doing fine, but when using star-rating.js from the bundle I get following error. Any idea?
![screenshot from 2016-05-22 16-51-43](https://cloud.githubusercontent.com/assets/10334123/15454600/044c1310-203e-11e6-9420-c4dbec655f6d.png)
