### ISSUE TITLE
RTL demo for two stars flickers in Chrome on Android

### ISSUE THREAD

**Issue by dandv** [kartik-v/bootstrap-star-rating#150]
Screencast: https://youtu.be/MnGT6q93hKM

**Comment by kartik-v** [comment]
It is because of the content window width and not related to the stars.

What is happening is you have a small content window and a caption displayed to the left as **Two Stars**

When the stars are changed to 3 ... the caption to the left changes to **Three Stars**,  but there is no space for that to be rendered to the left of the stars and it wraps down causing your effect.
