### ISSUE TITLE
怎样在 bootstrap 4  中使用

### ISSUE THREAD

**Issue by rockmelodies** [kartik-v/bootstrap-star-rating#186]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-star-rating.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-star-rating version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/star-rating/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-star-rating without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
For Bootstrap 4 - just load the Bootstrap 4 CSS and JS and use one of the other themes in the plugin instead of the default glyphicons theme,

- [Krajee Unicode Theme](http://plugins.krajee.com/star-rating-demo-theme-uni)
- [Krajee SVG Theme](http://plugins.krajee.com/star-rating-demo-theme-svg)
- [Krajee Font Awesome Theme](http://plugins.krajee.com/star-rating-demo-theme-fa) - use with Font Awesome icons
