### ISSUE TITLE
bootstrap 4 problem

### ISSUE THREAD

**Issue by kia1349** [kartik-v/bootstrap-star-rating#196]
first thank you for this light and best plugin

second , i could not use it with bootstrap 4 yet

can you update example folder using with bootstrap 4

**Comment by kartik-v** [comment]
Bootstrap 4.x does not need any special changes except using your own FONT ICON library - because Bootstrap 4.x does not include glyphicons.

The [demo site]((http://plugins.krajee.com/star-rating/demo) uses Bootstrap 4.x as the CSS library. Use any of the themes other than the Krajee Default Theme (for example use any of the following themes which will work with Bootstrap 4.x):

- [Krajee SVG Theme](http://plugins.krajee.com/star-rating-demo-theme-svg)
- [Krajee Font Awesome 5.x Theme](http://plugins.krajee.com/star-rating-demo-theme-fas)
- [Krajee Unicode Theme](http://plugins.krajee.com/star-rating-demo-theme-uni)
- [Krajee Font Awesome 4.x Theme](http://plugins.krajee.com/star-rating-demo-theme-fa)

**Comment by kia1349** [comment]
thanks a lot
i test it
