### ISSUE TITLE
Range of allowed ratings

### ISSUE THREAD

**Issue by gittix09** [kartik-v/bootstrap-star-rating#43]
Hello!!
Thank you for this awesome plugin.
Maybe it's my fault but I can't find how to limit the range of allowed ratings.
ATTENTION: the min and max options allow the developer to set the starting/ending values of the stars, but that's not what I'm referring to.
What I would like to do:
- 5 stars
- values range is 0 to 10 (so each star = 2 points)
- ALLOWED rating range: if a user is a beginner reviewer he/she can only select between a specific range of values (for example 5-9)

Sure I could set min-max = 5-9 but that would be very confusing (since in the same page there are other read-only star ratings with 5 stars and 0-10 range).

**Comment by kartik-v** [comment]
You have the answer in your question itself... 
- you would either need to set min / max values based on user type, OR
- you would need to handle this using validation (throw alert) through your server code OR separate javascript based on the user type (that will alert if range is violated)

**Comment by gittix09** [comment]
Thank you very much for the advice!!

P.s. Couldn't this feature be a potential enhancement for a future version? (I saw that this issue was labled as 'question').

**Comment by kartik-v** [comment]
Unfortunately it is not a requirement which can be generalized ... because it depends on your individual application's use case. Its best left to the developer (for scenarios based on USER access etc. to code as needed for the scenario. The plugin does expose methods and events for the developer to use as needed. For example `disable` rating after user updates ... that's a scenario which can be achieved by calling the `disable` method after the `update` event... but I cannot generalize it for all.

**Comment by kartik-v** [comment]
While I did mention the above ... you are free to suggest a method to enhance or even create a PR for the same extending above? 

Many server side web frameworks (e.g. Yii 2) already easily allow you to add a validation rule that validates the min and max for fields... so these are not included OR overloaded in the plugin
