### ISSUE TITLE
Error: Cannot read property 'pageX' of undefined 

### ISSUE THREAD

**Issue by satyapatidar** [kartik-v/bootstrap-star-rating#71]
Kartik,

On Android chrome browser when we touch on stars **touchstart** and **touchend** event fires but in the **touchend** event we are not getting e.originalEvent.touches[0].pageX because as per this - http://stackoverflow.com/questions/7192563/touchend-event-properties post in the **touchend** event touches are actually set in the **changesTouches** property.

This errors is causing on this line:
```javascript
var ev = e.originalEvent, touches = ev.touches || ev.changedTouches, pos = self.getPosition(touches[0]);
```

Btw, touches property is there in the touchend also but it's empty collection.

Can you please fix this?

**Comment by bgaillard** [comment]
Hi, we encounter the same problem, it seems this is because `ev.touches` returns a `TouchList` (http://www.w3.org/TR/touch-events/#touchlist-interface) object which can never be `undefined` or `null`. 

So `ev.changedTouches` can never be encountered. Then when `self.getPosition(touches[0])` is called `touches[0]` is `undefined`. 

In our case we encounter the following error (tested using Chrome Dev Tools with device emulation enabled). 

```javascript
Uncaught TypeError: Cannot read property 'pageX' of undefinedRating.getPosition @ star-rating.js:76
    Rating.setTouch @ star-rating.js:163
    (anonymous function) @ star-rating.js:180
    jQuery.event.dispatch @ jquery.js:4435
    elemData.handle @ jquery.js:4121
```

So to fix this problem the code has to be replaced with this. 
```javascript
var ev = e.originalEvent, touches = ev.touches.length > 0 ? ev.touches : ev.changedTouches, pos = self.getPosition(touches[0]);
```

I'll provide a PR to fix this after writing this comment.

**Comment by bgaillard** [comment]
So I've provided a PR, if you want to pull the patched version without waiting for the PR to be merge simply change your bower or node dependency to the following and use the unminified version of the library.

```json
"bootstrap-star-rating" : "git@github.com:gomoob/bootstrap-star-rating.git#a749b64ba806c0cd0d60de3b78761f27e6d401bc",
```

Hope this helps.

**Comment by satyapatidar** [comment]
Wow amazed for so quick response!!

Thanks guys!

**Comment by satyapatidar** [comment]
Kartik,

Any idea why this is happening with 3.5.5?

bower bootstrap-star-rating#3.5.5       not-cached git://github.com/kartik-v/bootstrap-star-rating.git#3.5.5
bower bootstrap-star-rating#3.5.5          resolve git://github.com/kartik-v/bootstrap-star-rating.git#3.5.5
bower bootstrap-star-rating#3.5.5     ENORESTARGET No tag found that was able to satisfy 3.5.5

**Comment by satyapatidar** [comment]
I think release 3.5.5 needs to be created and tagged?
